-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 22:30:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Airline_Reservation_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `AirPort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirPort` ;

CREATE TABLE IF NOT EXISTS `AirPort` (
  `Airport_Code` INT NOT NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Airport_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airplane_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Airplane_Type` ;

CREATE TABLE IF NOT EXISTS `Airplane_Type` (
  `Type_name` VARCHAR(45) NOT NULL,
  `Max_Seats` INT NULL,
  `Company` VARCHAR(45) NULL,
  PRIMARY KEY (`Type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Can_Land`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Can_Land` ;

CREATE TABLE IF NOT EXISTS `Can_Land` (
  `Airport_Code` INT NOT NULL,
  `Airplane_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Airport_Code`, `Airplane_type_name`),
  INDEX `FK_AirplaneType_CanLand_idx` (`Airplane_type_name` ASC) VISIBLE,
  CONSTRAINT `FK_Airport_CanLand`
    FOREIGN KEY (`Airport_Code`)
    REFERENCES `AirPort` (`Airport_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AirplaneType_CanLand`
    FOREIGN KEY (`Airplane_type_name`)
    REFERENCES `Airplane_Type` (`Type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Airplane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Airplane` ;

CREATE TABLE IF NOT EXISTS `Airplane` (
  `Airplane_ID` INT NOT NULL,
  `Total_number_of_seats` INT NULL,
  `Airplane_Type_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Airplane_ID`),
  INDEX `FK_AirplaneType_Airplane_idx` (`Airplane_Type_Name` ASC) VISIBLE,
  CONSTRAINT `FK_AirplaneType_Airplane`
    FOREIGN KEY (`Airplane_Type_Name`)
    REFERENCES `Airplane_Type` (`Type_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Flight` ;

CREATE TABLE IF NOT EXISTS `Flight` (
  `Number` INT NOT NULL,
  `Airline` VARCHAR(45) NULL,
  `Weeksdays` DATE NULL,
  PRIMARY KEY (`Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flight_Leg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Flight_Leg` ;

CREATE TABLE IF NOT EXISTS `Flight_Leg` (
  `Leg_Number` INT NOT NULL,
  `Flight_Number` INT NOT NULL,
  `Arr_Leg_Airport_Code` INT NOT NULL,
  `Dep_Leg_Airport_Code` INT NOT NULL,
  `Scheduled_Dep_Time` TIME NULL,
  `Scheduled_Arr_Time` TIME NULL,
  PRIMARY KEY (`Leg_Number`, `Flight_Number`),
  INDEX `FK_DepAirport_FlightLeg_idx` (`Dep_Leg_Airport_Code` ASC) VISIBLE,
  INDEX `FK_ArrAirport_FlightLeg_idx` (`Arr_Leg_Airport_Code` ASC) VISIBLE,
  INDEX `FK_Flight_FlightLeg_idx` (`Flight_Number` ASC) VISIBLE,
  CONSTRAINT `FK_DepAirport_FlightLeg`
    FOREIGN KEY (`Dep_Leg_Airport_Code`)
    REFERENCES `AirPort` (`Airport_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ArrAirport_FlightLeg`
    FOREIGN KEY (`Arr_Leg_Airport_Code`)
    REFERENCES `AirPort` (`Airport_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Flight_FlightLeg`
    FOREIGN KEY (`Flight_Number`)
    REFERENCES `Flight` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Leg_Instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Leg_Instance` ;

CREATE TABLE IF NOT EXISTS `Leg_Instance` (
  `Date` DATE NOT NULL,
  `Leg_Number` INT NOT NULL,
  `Leg_Flight_Number` INT NOT NULL,
  `Dep_Leg_Airport_Code` INT NOT NULL,
  `Dep_Time` TIME NULL,
  `Arr_Leg_Airport_Code` INT NOT NULL,
  `Arr_Time` TIME NULL,
  `Assigned_Ariplane_ID` INT NOT NULL,
  `Number_of_Avail_Seats` INT NULL,
  PRIMARY KEY (`Date`, `Leg_Number`, `Leg_Flight_Number`),
  INDEX `FK_Airport_LegInstance_idx` (`Dep_Leg_Airport_Code` ASC) VISIBLE,
  INDEX `FK_ArrAirport_LegInstance_idx` (`Arr_Leg_Airport_Code` ASC) VISIBLE,
  INDEX `FK_Airplane_LegInstance_idx` (`Assigned_Ariplane_ID` ASC) VISIBLE,
  INDEX `FK_FlightLeg_LegInstance_idx` (`Leg_Number` ASC) VISIBLE,
  INDEX `FK_FlightLeg_LegInstance_idx1` (`Leg_Flight_Number` ASC) VISIBLE,
  CONSTRAINT `FK_DepAirport_LegInstance`
    FOREIGN KEY (`Dep_Leg_Airport_Code`)
    REFERENCES `AirPort` (`Airport_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ArrAirport_LegInstance`
    FOREIGN KEY (`Arr_Leg_Airport_Code`)
    REFERENCES `AirPort` (`Airport_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Airplane_LegInstance`
    FOREIGN KEY (`Assigned_Ariplane_ID`)
    REFERENCES `Airplane` (`Airplane_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FlightLeg_LegInstance`
    FOREIGN KEY (`Leg_Number`)
    REFERENCES `Flight_Leg` (`Leg_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FlightLeg_LegInstance`
    FOREIGN KEY (`Leg_Flight_Number`)
    REFERENCES `Flight_Leg` (`Flight_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Seat` ;

CREATE TABLE IF NOT EXISTS `Seat` (
  `Seat_Number` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Leg_Flight_Number` INT NOT NULL,
  `Leg_Number` INT NOT NULL,
  `Customer_Name` VARCHAR(45) NULL,
  `Cphone` INT NULL,
  PRIMARY KEY (`Seat_Number`, `Leg_Flight_Number`, `Leg_Number`, `Date`),
  INDEX `FK_LegInstance_Seat_idx` (`Date` ASC) VISIBLE,
  INDEX `FK_LegInstance_Seat_idx1` (`Leg_Flight_Number` ASC) VISIBLE,
  INDEX `FK_LegInstance_Seat_idx2` (`Leg_Number` ASC) VISIBLE,
  CONSTRAINT `FK_LegInstance_Seat(Date)`
    FOREIGN KEY (`Date`)
    REFERENCES `Leg_Instance` (`Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LegInstance_Seat(Leg_Flight_Number)`
    FOREIGN KEY (`Leg_Flight_Number`)
    REFERENCES `Leg_Instance` (`Leg_Flight_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LegInstance_Seat(Leg_Number)`
    FOREIGN KEY (`Leg_Number`)
    REFERENCES `Leg_Instance` (`Leg_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fare` ;

CREATE TABLE IF NOT EXISTS `Fare` (
  `Code` INT NOT NULL,
  `Flight_Number` INT NOT NULL,
  `Amount` INT NULL,
  `Restrictions` VARCHAR(45) NULL,
  PRIMARY KEY (`Code`, `Flight_Number`),
  INDEX `FK_Flight_Fare_idx` (`Flight_Number` ASC) VISIBLE,
  CONSTRAINT `FK_Flight_Fare`
    FOREIGN KEY (`Flight_Number`)
    REFERENCES `Flight` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
