-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 10:00:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema K-LeagueTest
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `K-LeagueTest` ;

-- -----------------------------------------------------
-- Schema K-LeagueTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `K-LeagueTest` DEFAULT CHARACTER SET utf8 ;
USE `K-LeagueTest` ;

-- -----------------------------------------------------
-- Table `Stadium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stadium` ;

CREATE TABLE IF NOT EXISTS `Stadium` (
  `Stadium_ID` INT NOT NULL,
  `Stadium_Name` VARCHAR(45) NULL,
  `Number_Of_Seats` INT NULL,
  PRIMARY KEY (`Stadium_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team` ;

CREATE TABLE IF NOT EXISTS `Team` (
  `Team_ID` INT NOT NULL,
  `Team_Name` VARCHAR(45) NULL,
  `Region` VARCHAR(45) NULL,
  `Stadium_ID` INT NOT NULL,
  PRIMARY KEY (`Team_ID`),
  CONSTRAINT `FK_Stadium_Team`
    FOREIGN KEY (`Stadium_ID`)
    REFERENCES `Stadium` (`Stadium_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Stadium_Team_idx` ON `Team` (`Stadium_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game` ;

CREATE TABLE IF NOT EXISTS `Game` (
  `Stadium_ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `HomeTeam_ID` INT NOT NULL,
  `HomeTeam_Score` INT NULL,
  `AwayTeam_ID` INT NOT NULL,
  `AwayTeam_Score` INT NULL,
  PRIMARY KEY (`Stadium_ID`, `Date`),
  CONSTRAINT `FK_Stadium_Game`
    FOREIGN KEY (`Stadium_ID`)
    REFERENCES `Stadium` (`Stadium_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_HomeTeam_Game`
    FOREIGN KEY (`HomeTeam_ID`)
    REFERENCES `Team` (`Team_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AwayTeam_Game`
    FOREIGN KEY (`AwayTeam_ID`)
    REFERENCES `Team` (`Team_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_HomeTeam_Game_idx` ON `Game` (`HomeTeam_ID` ASC) VISIBLE;

CREATE INDEX `FK_AwayTeam_Game_idx` ON `Game` (`AwayTeam_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Player` ;

CREATE TABLE IF NOT EXISTS `Player` (
  `Player_ID` INT NOT NULL,
  `Player_Name` VARCHAR(45) NULL,
  `Player_Position` VARCHAR(45) NULL,
  `Player_Backnumber` INT NULL,
  `Team_ID` INT NULL,
  PRIMARY KEY (`Player_ID`),
  CONSTRAINT `FK_Team_Player`
    FOREIGN KEY (`Team_ID`)
    REFERENCES `Team` (`Team_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Team_Player_idx` ON `Player` (`Team_ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
